FROM node:alpine AS runner
RUN apk add --no-cache libc6-compat
COPY . .
EXPOSE 3000
ENV NODE_OPTIONS=--openssl-legacy-provider

ARG ARG_NEXT_PUBLIC_KRATOS_PUBLIC_API="https://kratosdev.bootlabstech.com/"
ARG ARG_NEXT_PUBLIC_HOSTPORT=""
ARG ARG_NEXT_PUBLIC_BUCKET_NAME=""
ARG ARG_NEXT_PUBLIC_PRODUCT_NAME=""
ARG ARG_BACKEND_API="https://sailordev.bootlabstech.com"
ENV NEXT_PRIVATE_KRATOS_IDENTITY_API="http://kratos-admin/"
ENV NEXT_PUBLIC_KRATOS_PUBLIC_API=$ARG_NEXT_PUBLIC_KRATOS_PUBLIC_API
ENV NEXT_PUBLIC_BUCKET_NAME=$ARG_NEXT_PUBLIC_BUCKET_NAME
ENV NEXT_PUBLIC_HOSTPORT=$ARG_NEXT_PUBLIC_HOSTPORT
ENV NEXT_PUBLIC_PRODUCT_NAME=$ARG_NEXT_PUBLIC_PRODUCT_NAME
ENV BACKEND_API=$ARG_BACKEND_API
RUN npm install --force
RUN npm run build
CMD ["npm", "run", "start"]

